# Screen and cells
SCREEN_MAP_X_SIZE = 1000
SCREEN_MAP_Y_SIZE = 600
PANEL_Y_SIZE = 80
NUMBER_OF_X_CELLS = 80
SUP_LIM_OF_X_CELLS = 300
INF_LIM_OF_X_CELLS = 20
CELLSIZE = SCREEN_MAP_X_SIZE / NUMBER_OF_X_CELLS
NUMBER_OF_Y_CELLS = int( SCREEN_MAP_Y_SIZE  / CELLSIZE)

#Others
NEXT_GENERATION_WAIT_TIME = 50
INCREASE_NUMBER_OF_CELLS = 1
DECREASE_NUMBER_OF_CELLS = 1

#Buttons
START_BUTTON_X_SIZE = 100
START_BUTTON_Y_SIZE = 40
START_BUTTON_X = SCREEN_MAP_X_SIZE - START_BUTTON_X_SIZE - 240 
START_BUTTON_Y = SCREEN_MAP_Y_SIZE + 15

RANDOM_BUTTON_X_SIZE = 100
RANDOM_BUTTON_Y_SIZE = 40
RANDOM_BUTTON_X = START_BUTTON_X + START_BUTTON_X_SIZE + 10
RANDOM_BUTTON_Y = START_BUTTON_Y

RESET_BUTTON_X_SIZE = 100
RESET_BUTTON_Y_SIZE = 40
RESET_BUTTON_X = RANDOM_BUTTON_X + RANDOM_BUTTON_X_SIZE + 10
RESET_BUTTON_Y = START_BUTTON_Y

DECREASE_CELLS_X_SIZE = 30
DECREASE_CELLS_Y_SIZE = 30
DECREASE_CELLS_BUTTON_X = START_BUTTON_X - DECREASE_CELLS_X_SIZE - 10
DECREASE_CELLS_BUTTON_Y = START_BUTTON_Y + 5

INCREASE_CELLS_X_SIZE = 30
INCREASE_CELLS_Y_SIZE = 30
INCREASE_CELLS_BUTTON_X = DECREASE_CELLS_BUTTON_X - INCREASE_CELLS_X_SIZE - 10
INCREASE_CELLS_BUTTON_Y = START_BUTTON_Y + 5

